name: Build and Push Docker Image 

on:
  push:
    branches: [ main, develop ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  security-events: write
  actions: read

env:
  DOCKER_REGISTRY: docker.io
  IMAGE_NAME: elasticsearch-r2

jobs:
  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Hadolint Dockerfile linter
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: Dockerfile
        format: sarif
        output-file: hadolint-results.sarif

    - name: Upload Hadolint scan results
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      continue-on-error: true
      with:
        sarif_file: 'hadolint-results.sarif'

    - name: Show Hadolint results (if SARIF upload failed)
      if: always()
      run: |
        echo "📋 Hadolint Results:"
        cat hadolint-results.sarif | jq -r '.runs[0].results[]? | "❌ \(.ruleId): \(.message.text)"' || echo "✅ No Hadolint issues found"

    - name: Check base image is official Elasticsearch
      run: |
        if ! grep -q "FROM docker.elastic.co/elasticsearch/elasticsearch:" Dockerfile; then
          echo "Warning: Not using official Elasticsearch image from docker.elastic.co"
          echo "Please use: FROM docker.elastic.co/elasticsearch/elasticsearch:VERSION"
          exit 1
        fi
        echo "✅ Using official Elasticsearch image"

  build:
    runs-on: ubuntu-latest
    needs: security-scan
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        platforms: linux/arm64,linux/amd64
    
    - name: Log in to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}
    
    - name: Build for scanning (ARM64 primary)
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/arm64
        load: true
        tags: ${{ env.IMAGE_NAME }}:scan
        cache-from: type=gha
        cache-to: type=gha,mode=max

    # Security scanning of built image
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ env.IMAGE_NAME }}:scan
        format: 'sarif'
        output: 'trivy-results.sarif'
        severity: 'CRITICAL,HIGH'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      continue-on-error: true
      with:
        sarif_file: 'trivy-results.sarif'

    - name: Run Trivy vulnerability scanner (Table format)
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ env.IMAGE_NAME }}:scan
        format: 'table'
        severity: 'CRITICAL,HIGH'

    - name: Docker Scout CVE scan
      uses: docker/scout-action@v1
      if: github.event_name != 'pull_request'
      with:
        command: cves
        image: ${{ env.IMAGE_NAME }}:scan
        sarif-file: scout-report.sarif
        summary: true

    - name: Upload Docker Scout scan results
      uses: github/codeql-action/upload-sarif@v3
      if: always() && github.event_name != 'pull_request'
      continue-on-error: true
      with:
        sarif_file: 'scout-report.sarif'

    - name: Build and push (ARM64 primary, multi-platform)
      uses: docker/build-push-action@v5
      if: github.event_name != 'pull_request'
      with:
        context: .
        platforms: linux/arm64,linux/amd64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha

    - name: Update Docker Hub description
      if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
      uses: peter-evans/dockerhub-description@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        repository: ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}
        readme-filepath: ./README.md